/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Canova
 */
public class FrmTelaInicial extends javax.swing.JFrame {

    public FrmTelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelImagemFundo1 = new Controller.PainelImagemFundo();
        painelImagemFundo2 = new Controller.PainelImagemFundo();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnentrarcadpac = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Tela_InicialImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TELA INICIAL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 111, 22);

        jButton1.setText("CADASTRAR MÉDICO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 380, 200, 105);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(252, 206, 0, 0);

        btnentrarcadpac.setText("CADASTRAR PACIENTE");
        btnentrarcadpac.setMaximumSize(new java.awt.Dimension(137, 23));
        btnentrarcadpac.setMinimumSize(new java.awt.Dimension(137, 23));
        btnentrarcadpac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarcadpacActionPerformed(evt);
            }
        });
        jPanel1.add(btnentrarcadpac);
        btnentrarcadpac.setBounds(270, 380, 210, 105);

        jButton2.setText("Excluir Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 260, 470, 105);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair-menu-2.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(363, 20, 120, 25);

        Tela_InicialImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela_Inicial.jpg"))); // NOI18N
        jPanel1.add(Tela_InicialImg);
        Tela_InicialImg.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        FrmExcluirConsulta exccon = new FrmExcluirConsulta();
        exccon.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FrmCadastroMedico med = new FrmCadastroMedico();
        med.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnentrarcadpacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarcadpacActionPerformed
        // TODO add your handling code here:

        FrmCadastrarPaciente cad = new FrmCadastrarPaciente();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnentrarcadpacActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int resposta = 0;

        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Mesmo Sair desta Tela");
        if (resposta == JOptionPane.YES_OPTION) {
            FrmLogin log = new FrmLogin();
            log.setVisible(true);
            dispose();
        } else if (resposta == JOptionPane.NO_OPTION) {
            FrmLogin log = new FrmLogin();
            log.setVisible(false);
        }
   
    }//GEN-LAST:event_jButton3ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                



}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tela_InicialImg;
    private javax.swing.JButton btnentrarcadpac;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private Controller.PainelImagemFundo painelImagemFundo1;
    private Controller.PainelImagemFundo painelImagemFundo2;
    // End of variables declaration//GEN-END:variables
}
